var annotated =
[
    [ "std", "namespacestd.html", [
      [ "hash< qarray< Nq > >", "structstd_1_1hash_3_01qarray_3_01Nq_01_4_01_4.html", "structstd_1_1hash_3_01qarray_3_01Nq_01_4_01_4" ],
      [ "hash< std::array< int, N > >", "structstd_1_1hash_3_01std_1_1array_3_01int_00_01N_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1array_3_01int_00_01N_01_4_01_4" ],
      [ "hash< std::array< qarray< Nq >, Nlegs > >", "structstd_1_1hash_3_01std_1_1array_3_01qarray_3_01Nq_01_4_00_01Nlegs_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1array_3_01qarray_3_01Nq_01_4_00_01Nlegs_01_4_01_4" ],
      [ "hash< std::array< size_t, 2 > >", "structstd_1_1hash_3_01std_1_1array_3_01size__t_00_012_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1array_3_01size__t_00_012_01_4_01_4" ],
      [ "hash< std::pair< qarray< Nq >, size_t > >", "structstd_1_1hash_3_01std_1_1pair_3_01qarray_3_01Nq_01_4_00_01size__t_01_4_01_4.html", "structstd_1_1hash_3_01std_1_1pair_3_01qarray_3_01Nq_01_4_00_01size__t_01_4_01_4" ],
      [ "hash< std::tuple< size_t, size_t, size_t, qarray< Nq >, qarray< Nq > > >", "structstd_1_1hash_3_01std_1_1tuple_3_01size__t_00_01size__t_00_01size__t_00_01qarray_3_01Nq_01_4c3b2075fee2e17e8b0f7d1a3920ed04a.html", "structstd_1_1hash_3_01std_1_1tuple_3_01size__t_00_01size__t_00_01size__t_00_01qarray_3_01Nq_01_4c3b2075fee2e17e8b0f7d1a3920ed04a" ]
    ] ],
    [ "Sym", "namespaceSym.html", [
      [ "AltSpinSU2", "structSym_1_1AltSpinSU2.html", "structSym_1_1AltSpinSU2" ],
      [ "ChargeDn", "structSym_1_1ChargeDn.html", "structSym_1_1ChargeDn" ],
      [ "ChargeSU2", "structSym_1_1ChargeSU2.html", "structSym_1_1ChargeSU2" ],
      [ "ChargeU1", "structSym_1_1ChargeU1.html", "structSym_1_1ChargeU1" ],
      [ "ChargeUp", "structSym_1_1ChargeUp.html", "structSym_1_1ChargeUp" ],
      [ "ChargeZ2", "structSym_1_1ChargeZ2.html", "structSym_1_1ChargeZ2" ],
      [ "Momentum", "structSym_1_1Momentum.html", "structSym_1_1Momentum" ],
      [ "S1xS2", "classSym_1_1S1xS2.html", "classSym_1_1S1xS2" ],
      [ "SpinSU2", "structSym_1_1SpinSU2.html", "structSym_1_1SpinSU2" ],
      [ "SpinU1", "structSym_1_1SpinU1.html", "structSym_1_1SpinU1" ],
      [ "SU2", "classSym_1_1SU2.html", "classSym_1_1SU2" ],
      [ "SUN", "classSym_1_1SUN.html", "classSym_1_1SUN" ],
      [ "U0", "classSym_1_1U0.html", "classSym_1_1U0" ],
      [ "U1", "classSym_1_1U1.html", "classSym_1_1U1" ],
      [ "ZN", "classSym_1_1ZN.html", "classSym_1_1ZN" ]
    ] ],
    [ "VMPS", "namespaceVMPS.html", [
      [ "DIRECTION", "structVMPS_1_1DIRECTION.html", "structVMPS_1_1DIRECTION" ],
      [ "DoubleHeisenbergSU2", "classVMPS_1_1DoubleHeisenbergSU2.html", "classVMPS_1_1DoubleHeisenbergSU2" ],
      [ "Heisenberg", "classVMPS_1_1Heisenberg.html", "classVMPS_1_1Heisenberg" ],
      [ "HeisenbergSU2", "classVMPS_1_1HeisenbergSU2.html", "classVMPS_1_1HeisenbergSU2" ],
      [ "HeisenbergU1", "classVMPS_1_1HeisenbergU1.html", "classVMPS_1_1HeisenbergU1" ],
      [ "HeisenbergU1Complex", "classVMPS_1_1HeisenbergU1Complex.html", "classVMPS_1_1HeisenbergU1Complex" ],
      [ "HeisenbergU1XXZ", "classVMPS_1_1HeisenbergU1XXZ.html", "classVMPS_1_1HeisenbergU1XXZ" ],
      [ "HeisenbergXXZ", "classVMPS_1_1HeisenbergXXZ.html", "classVMPS_1_1HeisenbergXXZ" ],
      [ "HeisenbergXYZ", "classVMPS_1_1HeisenbergXYZ.html", "classVMPS_1_1HeisenbergXYZ" ],
      [ "Hubbard", "classVMPS_1_1Hubbard.html", "classVMPS_1_1Hubbard" ],
      [ "HubbardComplex", "classVMPS_1_1HubbardComplex.html", "classVMPS_1_1HubbardComplex" ],
      [ "HubbardSU2", "classVMPS_1_1HubbardSU2.html", "classVMPS_1_1HubbardSU2" ],
      [ "HubbardSU2charge", "classVMPS_1_1HubbardSU2charge.html", "classVMPS_1_1HubbardSU2charge" ],
      [ "HubbardSU2xSU2", "classVMPS_1_1HubbardSU2xSU2.html", "classVMPS_1_1HubbardSU2xSU2" ],
      [ "HubbardSU2xU1", "classVMPS_1_1HubbardSU2xU1.html", "classVMPS_1_1HubbardSU2xU1" ],
      [ "HubbardSU2xU1xZN", "classVMPS_1_1HubbardSU2xU1xZN.html", "classVMPS_1_1HubbardSU2xU1xZN" ],
      [ "HubbardU1", "classVMPS_1_1HubbardU1.html", "classVMPS_1_1HubbardU1" ],
      [ "HubbardU1spin", "classVMPS_1_1HubbardU1spin.html", "classVMPS_1_1HubbardU1spin" ],
      [ "HubbardU1xSU2", "classVMPS_1_1HubbardU1xSU2.html", "classVMPS_1_1HubbardU1xSU2" ],
      [ "HubbardU1xU1", "classVMPS_1_1HubbardU1xU1.html", "classVMPS_1_1HubbardU1xU1" ],
      [ "HubbardZ2", "classVMPS_1_1HubbardZ2.html", "classVMPS_1_1HubbardZ2" ],
      [ "KondoNecklace", "classVMPS_1_1KondoNecklace.html", "classVMPS_1_1KondoNecklace" ],
      [ "KondoNecklaceSU2", "classVMPS_1_1KondoNecklaceSU2.html", "classVMPS_1_1KondoNecklaceSU2" ],
      [ "KondoNecklaceU1", "classVMPS_1_1KondoNecklaceU1.html", "classVMPS_1_1KondoNecklaceU1" ],
      [ "KondoSU2xSU2", "classVMPS_1_1KondoSU2xSU2.html", "classVMPS_1_1KondoSU2xSU2" ],
      [ "KondoSU2xU1", "classVMPS_1_1KondoSU2xU1.html", "classVMPS_1_1KondoSU2xU1" ],
      [ "KondoU0xSU2", "classVMPS_1_1KondoU0xSU2.html", "classVMPS_1_1KondoU0xSU2" ],
      [ "KondoU1", "classVMPS_1_1KondoU1.html", "classVMPS_1_1KondoU1" ],
      [ "KondoU1xSU2", "classVMPS_1_1KondoU1xSU2.html", "classVMPS_1_1KondoU1xSU2" ],
      [ "KondoU1xU1", "classVMPS_1_1KondoU1xU1.html", "classVMPS_1_1KondoU1xU1" ],
      [ "PeierlsHubbardSU2charge", "classVMPS_1_1PeierlsHubbardSU2charge.html", "classVMPS_1_1PeierlsHubbardSU2charge" ],
      [ "PeierlsHubbardSU2xU1", "classVMPS_1_1PeierlsHubbardSU2xU1.html", "classVMPS_1_1PeierlsHubbardSU2xU1" ],
      [ "PeierlsHubbardSU2xU1xZN", "classVMPS_1_1PeierlsHubbardSU2xU1xZN.html", "classVMPS_1_1PeierlsHubbardSU2xU1xZN" ],
      [ "PeierlsHubbardU1", "classVMPS_1_1PeierlsHubbardU1.html", "classVMPS_1_1PeierlsHubbardU1" ],
      [ "PeierlsHubbardU1xSU2", "classVMPS_1_1PeierlsHubbardU1xSU2.html", "classVMPS_1_1PeierlsHubbardU1xSU2" ],
      [ "PeierlsHubbardU1xU1", "classVMPS_1_1PeierlsHubbardU1xU1.html", "classVMPS_1_1PeierlsHubbardU1xU1" ],
      [ "PeierlsHubbardU1xZN", "classVMPS_1_1PeierlsHubbardU1xZN.html", "classVMPS_1_1PeierlsHubbardU1xZN" ],
      [ "SpinlessFermions", "classVMPS_1_1SpinlessFermions.html", "classVMPS_1_1SpinlessFermions" ],
      [ "SpinlessFermionsU1", "classVMPS_1_1SpinlessFermionsU1.html", "classVMPS_1_1SpinlessFermionsU1" ],
      [ "SpinlessFermionsZ2", "classVMPS_1_1SpinlessFermionsZ2.html", "classVMPS_1_1SpinlessFermionsZ2" ]
    ] ],
    [ "Basis", "classBasis.html", "classBasis" ],
    [ "Biped", "structBiped.html", "structBiped" ],
    [ "Blocker", "classBlocker.html", "classBlocker" ],
    [ "DMRG", "structDMRG.html", "structDMRG" ],
    [ "DmrgJanitor", "classDmrgJanitor.html", "classDmrgJanitor" ],
    [ "DmrgSolver", "classDmrgSolver.html", "classDmrgSolver" ],
    [ "DoubleHeisenbergObservables", "classDoubleHeisenbergObservables.html", "classDoubleHeisenbergObservables" ],
    [ "EDSolver", "classEDSolver.html", "classEDSolver" ],
    [ "EntropyObserver", "classEntropyObserver.html", "classEntropyObserver" ],
    [ "FermionBase", "classFermionBase.html", "classFermionBase" ],
    [ "FermionSite", "classFermionSite.html", "classFermionSite" ],
    [ "FermionSite< Sym::S1xS2< Sym::S1xS2< Sym::SU2< Sym::SpinSU2 >, Sym::U1< Sym::ChargeU1 > >, Sym::ZN< Sym::Momentum, YMOMENTUM > > >", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01Scde795b0e79610a2c4ded430ed682683.html", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01Scde795b0e79610a2c4ded430ed682683" ],
    [ "FermionSite< Sym::S1xS2< Sym::SU2< Sym::SpinSU2 >, Sym::SU2< Sym::ChargeSU2 > > >", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01Sym_1_1SU2_3_01Sym_1_1ChargeSU2_01_4_01_4_01_4.html", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01Sym_1_1SU2_3_01Sym_1_1ChargeSU2_01_4_01_4_01_4" ],
    [ "FermionSite< Sym::S1xS2< Sym::SU2< Sym::SpinSU2 >, Sym::U1< Sym::ChargeU1 > > >", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01Sym_1_1U1_3_01Sym_1_1ChargeU1_01_4_01_4_01_4.html", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01Sym_1_1U1_3_01Sym_1_1ChargeU1_01_4_01_4_01_4" ],
    [ "FermionSite< Sym::S1xS2< Sym::U1< Sym::SpinU1 >, Sym::SU2< Sym::ChargeSU2 > > >", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1U1_3_01Sym_1_1SpinU1_01_4_00_01Sym_1_1SU2_3_01Sym_1_1ChargeSU2_01_4_01_4_01_4.html", "classFermionSite_3_01Sym_1_1S1xS2_3_01Sym_1_1U1_3_01Sym_1_1SpinU1_01_4_00_01Sym_1_1SU2_3_01Sym_1_1ChargeSU2_01_4_01_4_01_4" ],
    [ "FermionSite< Sym::SU2< Sym::ChargeSU2 > >", "classFermionSite_3_01Sym_1_1SU2_3_01Sym_1_1ChargeSU2_01_4_01_4.html", "classFermionSite_3_01Sym_1_1SU2_3_01Sym_1_1ChargeSU2_01_4_01_4" ],
    [ "FermionSite< Sym::SU2< Sym::SpinSU2 > >", "classFermionSite_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_01_4.html", "classFermionSite_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_01_4" ],
    [ "GAUGE", "structGAUGE.html", "structGAUGE" ],
    [ "GaussianRandomVector< MpoTransferVector< Symmetry, Scalar >, Scalar >", "structGaussianRandomVector_3_01MpoTransferVector_3_01Symmetry_00_01Scalar_01_4_00_01Scalar_01_4.html", "structGaussianRandomVector_3_01MpoTransferVector_3_01Symmetry_00_01Scalar_01_4_00_01Scalar_01_4" ],
    [ "GaussianRandomVector< PivotVector< Symmetry, Scalar_ >, Scalar_ >", "structGaussianRandomVector_3_01PivotVector_3_01Symmetry_00_01Scalar___01_4_00_01Scalar___01_4.html", "structGaussianRandomVector_3_01PivotVector_3_01Symmetry_00_01Scalar___01_4_00_01Scalar___01_4" ],
    [ "GaussianRandomVector< TransferVector< Symmetry, Scalar >, Scalar >", "structGaussianRandomVector_3_01TransferVector_3_01Symmetry_00_01Scalar_01_4_00_01Scalar_01_4.html", "structGaussianRandomVector_3_01TransferVector_3_01Symmetry_00_01Scalar_01_4_00_01Scalar_01_4" ],
    [ "GreenPropagator", "classGreenPropagator.html", "classGreenPropagator" ],
    [ "GreenPropagatorGlobal", "structGreenPropagatorGlobal.html", "structGreenPropagatorGlobal" ],
    [ "GreenPropagatorLog", "structGreenPropagatorLog.html", "structGreenPropagatorLog" ],
    [ "HamiltonianTerms", "classHamiltonianTerms.html", "classHamiltonianTerms" ],
    [ "HeisenbergObservables", "classHeisenbergObservables.html", "classHeisenbergObservables" ],
    [ "HubbardKspace", "classHubbardKspace.html", "classHubbardKspace" ],
    [ "HubbardObservables", "classHubbardObservables.html", "classHubbardObservables" ],
    [ "jEigenstate", "structjEigenstate.html", "structjEigenstate" ],
    [ "KondoNecklaceObservables", "classKondoNecklaceObservables.html", "classKondoNecklaceObservables" ],
    [ "KondoObservables", "classKondoObservables.html", "classKondoObservables" ],
    [ "KspaceHTerms", "structKspaceHTerms.html", "structKspaceHTerms" ],
    [ "KspaceMpoTerms", "structKspaceMpoTerms.html", "structKspaceMpoTerms" ],
    [ "KspaceRawTerms", "structKspaceRawTerms.html", "structKspaceRawTerms" ],
    [ "Mpo", "classMpo.html", "classMpo" ],
    [ "MpoTerms", "classMpoTerms.html", "classMpoTerms" ],
    [ "MpoTransferMatrix", "structMpoTransferMatrix.html", "structMpoTransferMatrix" ],
    [ "MpoTransferVector", "structMpoTransferVector.html", "structMpoTransferVector" ],
    [ "Mps", "classMps.html", "classMps" ],
    [ "MpsBoundaries", "classMpsBoundaries.html", "classMpsBoundaries" ],
    [ "MpsCompressor", "classMpsCompressor.html", "classMpsCompressor" ],
    [ "Multipede", "structMultipede.html", "structMultipede" ],
    [ "NuclearInfo", "structNuclearInfo.html", "structNuclearInfo" ],
    [ "NuclearManager", "classNuclearManager.html", "classNuclearManager" ],
    [ "orbinfo", "structorbinfo.html", "structorbinfo" ],
    [ "orbital", "structorbital.html", "structorbital" ],
    [ "ParamReturner", "classParamReturner.html", "classParamReturner" ],
    [ "PivotMatrix0", "structPivotMatrix0.html", "structPivotMatrix0" ],
    [ "PivotMatrix1", "structPivotMatrix1.html", "structPivotMatrix1" ],
    [ "PivotMatrix1Terms", "structPivotMatrix1Terms.html", "structPivotMatrix1Terms" ],
    [ "PivotMatrix2", "structPivotMatrix2.html", "structPivotMatrix2" ],
    [ "PivotMatrix2Terms", "structPivotMatrix2Terms.html", "structPivotMatrix2Terms" ],
    [ "PivotOverlap1", "structPivotOverlap1.html", "structPivotOverlap1" ],
    [ "PivotOverlap2", "structPivotOverlap2.html", "structPivotOverlap2" ],
    [ "PivotVector", "structPivotVector.html", "structPivotVector" ],
    [ "PivumpsMatrix0", "structPivumpsMatrix0.html", "structPivumpsMatrix0" ],
    [ "PivumpsMatrix1", "structPivumpsMatrix1.html", "structPivumpsMatrix1" ],
    [ "PushType", "structPushType.html", "structPushType" ],
    [ "qarray", "structqarray.html", "structqarray" ],
    [ "Qbasis", "classQbasis.html", "classQbasis" ],
    [ "refEnergy", "structrefEnergy.html", "structrefEnergy" ],
    [ "SiteOperator", "structSiteOperator.html", "structSiteOperator" ],
    [ "SiteOperatorQ", "classSiteOperatorQ.html", "classSiteOperatorQ" ],
    [ "SpectralManager", "classSpectralManager.html", "classSpectralManager" ],
    [ "SpinBase", "classSpinBase.html", "classSpinBase" ],
    [ "SpinlessFermionBase", "classSpinlessFermionBase.html", "classSpinlessFermionBase" ],
    [ "SpinlessFermionSite", "classSpinlessFermionSite.html", "classSpinlessFermionSite" ],
    [ "SpinlessFermionsObservables", "classSpinlessFermionsObservables.html", "classSpinlessFermionsObservables" ],
    [ "SpinlessSpinlessFermionBase", "classSpinlessSpinlessFermionBase.html", null ],
    [ "SpinSite", "classSpinSite.html", "classSpinSite" ],
    [ "SpinSite< Sym::S1xS2< OtherSym, Sym::SU2< Sym::SpinSU2 > >, 1ul >", "classSpinSite_3_01Sym_1_1S1xS2_3_01OtherSym_00_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_01_4_00_011ul_01_4.html", "classSpinSite_3_01Sym_1_1S1xS2_3_01OtherSym_00_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_01_4_00_011ul_01_4" ],
    [ "SpinSite< Sym::S1xS2< Sym::SU2< Sym::SpinSU2 >, OtherSym >, order >", "classSpinSite_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01OtherSym_01_4_00_01order_01_4.html", "classSpinSite_3_01Sym_1_1S1xS2_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_01OtherSym_01_4_00_01order_01_4" ],
    [ "SpinSite< Sym::SU2< Sym::SpinSU2 >, 0ul >", "classSpinSite_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_010ul_01_4.html", "classSpinSite_3_01Sym_1_1SU2_3_01Sym_1_1SpinSU2_01_4_00_010ul_01_4" ],
    [ "SuperMatrix", "classSuperMatrix.html", "classSuperMatrix" ],
    [ "SweepStatus", "structSweepStatus.html", "structSweepStatus" ],
    [ "TDVPPropagator", "classTDVPPropagator.html", "classTDVPPropagator" ],
    [ "TEBDPropagator", "classTEBDPropagator.html", "classTEBDPropagator" ],
    [ "TransferMatrix", "structTransferMatrix.html", "structTransferMatrix" ],
    [ "TransferMatrixQ", "structTransferMatrixQ.html", "structTransferMatrixQ" ],
    [ "TransferMatrixSF", "structTransferMatrixSF.html", "structTransferMatrixSF" ],
    [ "TransferVector", "structTransferVector.html", "structTransferVector" ],
    [ "TwoSiteData", "structTwoSiteData.html", "structTwoSiteData" ],
    [ "TwoSiteGate", "classTwoSiteGate.html", "classTwoSiteGate" ],
    [ "Umps", "classUmps.html", "classUmps" ],
    [ "UMPS_ALG", "structUMPS__ALG.html", "structUMPS__ALG" ],
    [ "UmpsCompressor", "classUmpsCompressor.html", "classUmpsCompressor" ],
    [ "VUMPS", "structVUMPS.html", "structVUMPS" ],
    [ "VumpsSolver", "classVumpsSolver.html", "classVumpsSolver" ]
];